### ISSUE TITLE
Similar framework

### ISSUE THREAD

**Issue by linsyking** [Orasund/pixelengine#2]
I wrote a 2D Elm game framework called [Messenger](https://github.com/linsyking/Messenger) and it has many nice features.

Our team developed a game called [Reweave](https://github.com/linsyking/Reweave) based on this framework.

I think Messenger are more flexible and you can use it to design almost any game (modularized, object-oriented).

I would appreciate if you could let me add a link to my project in your Readme. I hope that more people can see my framework :)

Hope you like our framework & game!

**Comment by Orasund** [comment]
I am hesitant to recommend a framework that is not an elm library. Usually, it is possible to write a framework such that you can publish it as a normal elm package. (see elm-canvas as an example).

**Comment by linsyking** [comment]
> I am hesitant to recommend a framework that is not an elm library. Usually, it is possible to write a framework such that you can publish it as a normal elm package. (see elm-canvas as an example).

Hi, currently Messenger is designed to be a game engine and is built as an elm library. All the core functions are moved to the [messenger-core](https://package.elm-lang.org/packages/linsyking/messenger-core/latest) package.

**Comment by Orasund** [comment]
I don't believe my package is the right place to promote your library.

[awesome-elm-gamedev](https://github.com/rofrol/awesome-elm-gamedev) should be a better place for it.
